---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/assets/content/blog
  label: Blog Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: src/assets/content/bio
  label: Bios
  create: documents
  match: "**/*"
  templates:
  - bio
- type: directory
  path: content/dictionary
  label: Dictionary entries
  create: documents
  match: "**/*"
  templates:
  - dictionary-entry
- type: heading
  label: Taxonomy
- type: directory
  path: src/assets/content/vocabulary
  label: All Vocabularies
  create: all
  match: "**/*"
  templates:
  - vocabulary
- type: document
  path: src/assets/content/vocabulary/roles.md
  label: Roles
- type: heading
  label: Config
- type: document
  path: src/assets/content/data/info.json
  label: Info Page
- type: document
  path: src/assets/content/data/config.json
  label: Site Config
upload_dir: src/assets/content/images
public_path: "/src/assets/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
